    ; asm file generated by eCompiler from ../data/main.ts
section .text
    global main
    extern printf
    
section .bss    ; uninitialized variables
    i resb 4
    t1 resb 4
    t2 resb 4
    
section .data    ; strings and other big stuff
    fmtd db '%d', 10, 0
    fmtf db '%f', 10, 0
    fmtc db '%c', 10, 0
    fmtb db '%d', 10, 0
    
main:
L1:
    mov eax, 5
    mov ebx, 10
    imul eax, ebx
    mov [t1], eax
    mov eax, 2
    mov ebx, 10
    imul eax, ebx
    mov [t2], eax
    mov eax, [t1]
    mov ebx, [t2]
    add eax, ebx
    mov [i], eax
L3:
    mov eax, [i]
    push eax
    push fmtd
    call printf
    add esp, 8
L2:
    mov eax, 1
    mov ebx, 0
    int 80h
