    ; asm file generated by eCompiler from ../data/main.ts
section .text
    global main
    extern printf
    
section .bss    ; uninitialized variables
    i resb 4
    j resb 1
    
section .data    ; strings and other big stuff
    line0 db 'counting...'
    lenLine0 equ $-line0
    line1 db 'here'
    lenLine1 equ $-line1
    fmtd db '%d', 10, 0
    fmtf db '%f', 10, 0
    fmtc db '%c', 10, 0
    fmtb db '%d', 10, 0
    
main:
L1:
    mov eax, 0
    mov [i], eax
L3:
    mov eax, [j]
    or eax, 0x01
    mov [j], eax
L4:
    mov eax, 4
    mov ebx, 1
    mov ecx, line0
    mov edx, lenLine0
    int 80h
L5:
    mov eax, [i]
    mov ebx, 10
    cmp eax, ebx
    jge L2
    mov eax, [j]
    cmp eax, 0x01
    jne L2
L6:
    mov eax, 4
    mov ebx, 1
    mov ecx, line1
    mov edx, lenLine1
    int 80h
L7:
    mov eax, [i]
    push eax
    push fmtd
    call printf
    add esp, 8
L8:
    mov eax, [i]
    mov ebx, 5
    cmp eax, ebx
    jne L9
L10:
    mov eax, [j]
    and eax, 0xFFFFFFFE
    mov [j], eax
L9:
    mov eax, [i]
    mov ebx, 1
    add eax, ebx
    mov [i], eax
    jmp L5
L2:
    mov eax, 1
    mov ebx, 0
    int 80h
